### ISSUE TITLE
Light toggle is insensitive to group on/off state

### ISSUE THREAD

**Issue by Vladimir-csp** [ChrisAdderley/NearFutureSpacecraft#44]
Parts with lights always switching to their opposite state when light action group is triggered, unlike stock parts, which toggle according to action group's on/off state.
Also those parts can not toggle back mid-animation, while stock parts can.  This all leads to desynchronized light state throughout the ship's parts.

It also affects SSPX parts.

**Comment by ChrisAdderley** [comment]
Here's a comparison between the Mk 3-9 and Mk3 cockpit relevant configurations. There doesn't seem to be any difference.
```
        MODULE
	{
		name = ModuleAnimateGeneric
		animationName = Mk3-9-Windows
		startEventGUIName = Lights On
		endEventGUIName = Lights Off
		actionGUIName = Toggle Lights
                defaultActionGroup = Light
	}
```
```
	MODULE
	{
		name = ModuleAnimateGeneric
		animationName = Mk3Cockpit_Shuttle
		actionGUIName = Toggle Lights
		defaultActionGroup = Light
		startEventGUIName = Lights On
		endEventGUIName = Lights Off
	}
```

**Comment by Vladimir-csp** [comment]
Yes, they are all the same, in SSPX also. But the difference in behavior exists.
Maybe something in animations themselves?

**Comment by ChrisAdderley** [comment]
Are you very sure that this is the case on *all* stock parts? There are two different methods of light animation handling.

**Comment by ChrisAdderley** [comment]
I confirmed that this issue is shared by all parts that use the ModuleAnimateGeneric method of creating an animation. This means most of the Porkjet stock parts (Mk2/3 cockpit/crew cabin) in particular. 

Maybe if SQUAD provides the proper code to make the animation module obey the same rules as the other module I will change this, but for now I don't see the point.
